// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saovvpejndlngwvcgqrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhb3Z2cGVqbmRsbmd3dmNncXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDE3NjksImV4cCI6MjA2OTY3Nzc2OX0.rtkXelWJnEqfx5JQNM6qmy8c_UxBb3IPPcp6V2-eI4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});